# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6652c17bacef88c5aece48488be5ebaa196c3950cb308f04725a99948afd9d13a6af29d712c7b7518e13b50fc4e24872c64cf99a11113843153b366c1c0fd8d

test:
  secret_key_base: 4cbb2c18790555f9c1d3b019707a487a4b384640c4b7c2f7f93f89c651fba86a3a4ed2870156b5ba70cbb1e8426048bcfb71988f3c3e235bb4790da7d86965da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
